// Code generated by protoc-gen-go. DO NOT EDIT.
// source: packet.proto

package ws

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Packet_ContentType int32

const (
	Packet_JSON Packet_ContentType = 0
)

var Packet_ContentType_name = map[int32]string{
	0: "JSON",
}

var Packet_ContentType_value = map[string]int32{
	"JSON": 0,
}

func (x Packet_ContentType) String() string {
	return proto.EnumName(Packet_ContentType_name, int32(x))
}

func (Packet_ContentType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e9ef1a6541f9f9e7, []int{0, 0}
}

type Packet struct {
	ContentType Packet_ContentType `protobuf:"varint,1,opt,name=contentType,proto3,enum=ws.Packet_ContentType" json:"contentType,omitempty"`
	// Types that are valid to be assigned to Content:
	//	*Packet_Call_
	//	*Packet_Reply_
	//	*Packet_Push
	Content              isPacket_Content `protobuf_oneof:"Content"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Packet) Reset()         { *m = Packet{} }
func (m *Packet) String() string { return proto.CompactTextString(m) }
func (*Packet) ProtoMessage()    {}
func (*Packet) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9ef1a6541f9f9e7, []int{0}
}

func (m *Packet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Packet.Unmarshal(m, b)
}
func (m *Packet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Packet.Marshal(b, m, deterministic)
}
func (m *Packet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Packet.Merge(m, src)
}
func (m *Packet) XXX_Size() int {
	return xxx_messageInfo_Packet.Size(m)
}
func (m *Packet) XXX_DiscardUnknown() {
	xxx_messageInfo_Packet.DiscardUnknown(m)
}

var xxx_messageInfo_Packet proto.InternalMessageInfo

func (m *Packet) GetContentType() Packet_ContentType {
	if m != nil {
		return m.ContentType
	}
	return Packet_JSON
}

type isPacket_Content interface {
	isPacket_Content()
}

type Packet_Call_ struct {
	Call *Packet_Call `protobuf:"bytes,2,opt,name=call,proto3,oneof"`
}

type Packet_Reply_ struct {
	Reply *Packet_Reply `protobuf:"bytes,3,opt,name=reply,proto3,oneof"`
}

type Packet_Push struct {
	Push []byte `protobuf:"bytes,4,opt,name=push,proto3,oneof"`
}

func (*Packet_Call_) isPacket_Content() {}

func (*Packet_Reply_) isPacket_Content() {}

func (*Packet_Push) isPacket_Content() {}

func (m *Packet) GetContent() isPacket_Content {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *Packet) GetCall() *Packet_Call {
	if x, ok := m.GetContent().(*Packet_Call_); ok {
		return x.Call
	}
	return nil
}

func (m *Packet) GetReply() *Packet_Reply {
	if x, ok := m.GetContent().(*Packet_Reply_); ok {
		return x.Reply
	}
	return nil
}

func (m *Packet) GetPush() []byte {
	if x, ok := m.GetContent().(*Packet_Push); ok {
		return x.Push
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Packet) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Packet_Call_)(nil),
		(*Packet_Reply_)(nil),
		(*Packet_Push)(nil),
	}
}

type Packet_Error struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Packet_Error) Reset()         { *m = Packet_Error{} }
func (m *Packet_Error) String() string { return proto.CompactTextString(m) }
func (*Packet_Error) ProtoMessage()    {}
func (*Packet_Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9ef1a6541f9f9e7, []int{0, 0}
}

func (m *Packet_Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Packet_Error.Unmarshal(m, b)
}
func (m *Packet_Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Packet_Error.Marshal(b, m, deterministic)
}
func (m *Packet_Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Packet_Error.Merge(m, src)
}
func (m *Packet_Error) XXX_Size() int {
	return xxx_messageInfo_Packet_Error.Size(m)
}
func (m *Packet_Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Packet_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Packet_Error proto.InternalMessageInfo

func (m *Packet_Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Packet_Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Packet_Call struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Data                 []byte   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Packet_Call) Reset()         { *m = Packet_Call{} }
func (m *Packet_Call) String() string { return proto.CompactTextString(m) }
func (*Packet_Call) ProtoMessage()    {}
func (*Packet_Call) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9ef1a6541f9f9e7, []int{0, 1}
}

func (m *Packet_Call) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Packet_Call.Unmarshal(m, b)
}
func (m *Packet_Call) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Packet_Call.Marshal(b, m, deterministic)
}
func (m *Packet_Call) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Packet_Call.Merge(m, src)
}
func (m *Packet_Call) XXX_Size() int {
	return xxx_messageInfo_Packet_Call.Size(m)
}
func (m *Packet_Call) XXX_DiscardUnknown() {
	xxx_messageInfo_Packet_Call.DiscardUnknown(m)
}

var xxx_messageInfo_Packet_Call proto.InternalMessageInfo

func (m *Packet_Call) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Packet_Call) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Packet_Call) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Packet_Reply struct {
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Types that are valid to be assigned to Result:
	//	*Packet_Reply_Data
	//	*Packet_Reply_Error
	Result               isPacket_Reply_Result `protobuf_oneof:"result"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Packet_Reply) Reset()         { *m = Packet_Reply{} }
func (m *Packet_Reply) String() string { return proto.CompactTextString(m) }
func (*Packet_Reply) ProtoMessage()    {}
func (*Packet_Reply) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9ef1a6541f9f9e7, []int{0, 2}
}

func (m *Packet_Reply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Packet_Reply.Unmarshal(m, b)
}
func (m *Packet_Reply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Packet_Reply.Marshal(b, m, deterministic)
}
func (m *Packet_Reply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Packet_Reply.Merge(m, src)
}
func (m *Packet_Reply) XXX_Size() int {
	return xxx_messageInfo_Packet_Reply.Size(m)
}
func (m *Packet_Reply) XXX_DiscardUnknown() {
	xxx_messageInfo_Packet_Reply.DiscardUnknown(m)
}

var xxx_messageInfo_Packet_Reply proto.InternalMessageInfo

func (m *Packet_Reply) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type isPacket_Reply_Result interface {
	isPacket_Reply_Result()
}

type Packet_Reply_Data struct {
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

type Packet_Reply_Error struct {
	Error *Packet_Error `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

func (*Packet_Reply_Data) isPacket_Reply_Result() {}

func (*Packet_Reply_Error) isPacket_Reply_Result() {}

func (m *Packet_Reply) GetResult() isPacket_Reply_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *Packet_Reply) GetData() []byte {
	if x, ok := m.GetResult().(*Packet_Reply_Data); ok {
		return x.Data
	}
	return nil
}

func (m *Packet_Reply) GetError() *Packet_Error {
	if x, ok := m.GetResult().(*Packet_Reply_Error); ok {
		return x.Error
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Packet_Reply) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Packet_Reply_Data)(nil),
		(*Packet_Reply_Error)(nil),
	}
}

func init() {
	proto.RegisterEnum("ws.Packet_ContentType", Packet_ContentType_name, Packet_ContentType_value)
	proto.RegisterType((*Packet)(nil), "ws.Packet")
	proto.RegisterType((*Packet_Error)(nil), "ws.Packet.Error")
	proto.RegisterType((*Packet_Call)(nil), "ws.Packet.Call")
	proto.RegisterType((*Packet_Reply)(nil), "ws.Packet.Reply")
}

func init() { proto.RegisterFile("packet.proto", fileDescriptor_e9ef1a6541f9f9e7) }

var fileDescriptor_e9ef1a6541f9f9e7 = []byte{
	// 313 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xcf, 0x6b, 0xfa, 0x30,
	0x14, 0xc0, 0x6d, 0x6d, 0xfd, 0xf1, 0x14, 0xbf, 0x12, 0xe4, 0xbb, 0xd0, 0x93, 0x08, 0x83, 0x9e,
	0x2a, 0x38, 0x06, 0x3b, 0xed, 0xe0, 0x18, 0xc8, 0x0e, 0xdb, 0xc8, 0x76, 0xda, 0x2d, 0xb6, 0x41,
	0xcb, 0x62, 0x13, 0x92, 0x94, 0xe2, 0x5f, 0xb4, 0x7f, 0x73, 0xe4, 0xa9, 0xac, 0xb0, 0xdd, 0xde,
	0x8f, 0xcf, 0x7b, 0x7c, 0x5e, 0x02, 0x63, 0xcd, 0xf3, 0x4f, 0xe1, 0x32, 0x6d, 0x94, 0x53, 0x24,
	0x6c, 0xec, 0xe2, 0xab, 0x0b, 0xbd, 0x57, 0x2c, 0x92, 0x3b, 0x18, 0xe5, 0xaa, 0x72, 0xa2, 0x72,
	0xef, 0x47, 0x2d, 0x68, 0x30, 0x0f, 0xd2, 0xc9, 0xea, 0x7f, 0xd6, 0xd8, 0xec, 0x04, 0x64, 0x0f,
	0x3f, 0x5d, 0xd6, 0x46, 0xc9, 0x35, 0x44, 0x39, 0x97, 0x92, 0x86, 0xf3, 0x20, 0x1d, 0xad, 0xfe,
	0xb5, 0x47, 0xb8, 0x94, 0x9b, 0x0e, 0xc3, 0x36, 0x49, 0x21, 0x36, 0x42, 0xcb, 0x23, 0xed, 0x22,
	0x37, 0x6d, 0x71, 0xcc, 0xd7, 0x37, 0x1d, 0x76, 0x02, 0xc8, 0x0c, 0x22, 0x5d, 0xdb, 0x3d, 0x8d,
	0xe6, 0x41, 0x3a, 0xf6, 0xf3, 0x3e, 0x4b, 0x6e, 0x21, 0x7e, 0x34, 0x46, 0x19, 0x42, 0x20, 0xca,
	0x55, 0x71, 0x52, 0x8c, 0x19, 0xc6, 0x84, 0x42, 0xff, 0x20, 0xac, 0xe5, 0x3b, 0x81, 0x1a, 0x43,
	0x76, 0x49, 0x93, 0x7b, 0x88, 0xbc, 0x06, 0x99, 0x40, 0x58, 0x16, 0xe7, 0x99, 0xb0, 0x2c, 0xfc,
	0x96, 0x8a, 0x1f, 0x2e, 0x38, 0xc6, 0xbe, 0x56, 0x70, 0xc7, 0xd1, 0x70, 0xcc, 0x30, 0x4e, 0x38,
	0xc4, 0xa8, 0xf7, 0x6b, 0xc1, 0xec, 0x0c, 0x87, 0x17, 0x4b, 0x9f, 0xf9, 0x2b, 0x85, 0xb7, 0xfc,
	0xe3, 0x4a, 0xb4, 0xf7, 0x57, 0x22, 0xb0, 0x1e, 0x40, 0xcf, 0x08, 0x5b, 0x4b, 0xb7, 0xb8, 0x82,
	0x51, 0xeb, 0x71, 0xc9, 0x00, 0xa2, 0xa7, 0xb7, 0x97, 0xe7, 0x69, 0x67, 0x3d, 0x84, 0xfe, 0xb9,
	0xb1, 0x4e, 0x3e, 0xe8, 0xae, 0x74, 0xfb, 0x7a, 0x9b, 0xe5, 0xea, 0xb0, 0xdc, 0x29, 0x5d, 0x6f,
	0x97, 0x4d, 0x59, 0x89, 0x65, 0x63, 0xb7, 0x3d, 0xfc, 0xd0, 0x9b, 0xef, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xcf, 0x56, 0x7e, 0x71, 0xe0, 0x01, 0x00, 0x00,
}
