// Code generated by protoc-gen-go. DO NOT EDIT.
// source: packet.proto

package ws

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Packet_ContentType int32

const (
	Packet_JSON Packet_ContentType = 0
)

var Packet_ContentType_name = map[int32]string{
	0: "JSON",
}

var Packet_ContentType_value = map[string]int32{
	"JSON": 0,
}

func (x Packet_ContentType) String() string {
	return proto.EnumName(Packet_ContentType_name, int32(x))
}

func (Packet_ContentType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e9ef1a6541f9f9e7, []int{3, 0}
}

type Error struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9ef1a6541f9f9e7, []int{0}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Call struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Data                 []byte   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Call) Reset()         { *m = Call{} }
func (m *Call) String() string { return proto.CompactTextString(m) }
func (*Call) ProtoMessage()    {}
func (*Call) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9ef1a6541f9f9e7, []int{1}
}

func (m *Call) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Call.Unmarshal(m, b)
}
func (m *Call) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Call.Marshal(b, m, deterministic)
}
func (m *Call) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Call.Merge(m, src)
}
func (m *Call) XXX_Size() int {
	return xxx_messageInfo_Call.Size(m)
}
func (m *Call) XXX_DiscardUnknown() {
	xxx_messageInfo_Call.DiscardUnknown(m)
}

var xxx_messageInfo_Call proto.InternalMessageInfo

func (m *Call) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Call) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Call) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Reply struct {
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Types that are valid to be assigned to Result:
	//	*Reply_Data
	//	*Reply_Error
	Result               isReply_Result `protobuf_oneof:"result"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Reply) Reset()         { *m = Reply{} }
func (m *Reply) String() string { return proto.CompactTextString(m) }
func (*Reply) ProtoMessage()    {}
func (*Reply) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9ef1a6541f9f9e7, []int{2}
}

func (m *Reply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Reply.Unmarshal(m, b)
}
func (m *Reply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Reply.Marshal(b, m, deterministic)
}
func (m *Reply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Reply.Merge(m, src)
}
func (m *Reply) XXX_Size() int {
	return xxx_messageInfo_Reply.Size(m)
}
func (m *Reply) XXX_DiscardUnknown() {
	xxx_messageInfo_Reply.DiscardUnknown(m)
}

var xxx_messageInfo_Reply proto.InternalMessageInfo

func (m *Reply) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type isReply_Result interface {
	isReply_Result()
}

type Reply_Data struct {
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

type Reply_Error struct {
	Error *Error `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

func (*Reply_Data) isReply_Result() {}

func (*Reply_Error) isReply_Result() {}

func (m *Reply) GetResult() isReply_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *Reply) GetData() []byte {
	if x, ok := m.GetResult().(*Reply_Data); ok {
		return x.Data
	}
	return nil
}

func (m *Reply) GetError() *Error {
	if x, ok := m.GetResult().(*Reply_Error); ok {
		return x.Error
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Reply) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Reply_Data)(nil),
		(*Reply_Error)(nil),
	}
}

type Packet struct {
	ContentType Packet_ContentType `protobuf:"varint,1,opt,name=contentType,proto3,enum=ws.Packet_ContentType" json:"contentType,omitempty"`
	// Types that are valid to be assigned to Content:
	//	*Packet_Call
	//	*Packet_Reply
	//	*Packet_Push
	Content              isPacket_Content `protobuf_oneof:"Content"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Packet) Reset()         { *m = Packet{} }
func (m *Packet) String() string { return proto.CompactTextString(m) }
func (*Packet) ProtoMessage()    {}
func (*Packet) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9ef1a6541f9f9e7, []int{3}
}

func (m *Packet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Packet.Unmarshal(m, b)
}
func (m *Packet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Packet.Marshal(b, m, deterministic)
}
func (m *Packet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Packet.Merge(m, src)
}
func (m *Packet) XXX_Size() int {
	return xxx_messageInfo_Packet.Size(m)
}
func (m *Packet) XXX_DiscardUnknown() {
	xxx_messageInfo_Packet.DiscardUnknown(m)
}

var xxx_messageInfo_Packet proto.InternalMessageInfo

func (m *Packet) GetContentType() Packet_ContentType {
	if m != nil {
		return m.ContentType
	}
	return Packet_JSON
}

type isPacket_Content interface {
	isPacket_Content()
}

type Packet_Call struct {
	Call *Call `protobuf:"bytes,2,opt,name=call,proto3,oneof"`
}

type Packet_Reply struct {
	Reply *Reply `protobuf:"bytes,3,opt,name=reply,proto3,oneof"`
}

type Packet_Push struct {
	Push []byte `protobuf:"bytes,4,opt,name=push,proto3,oneof"`
}

func (*Packet_Call) isPacket_Content() {}

func (*Packet_Reply) isPacket_Content() {}

func (*Packet_Push) isPacket_Content() {}

func (m *Packet) GetContent() isPacket_Content {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *Packet) GetCall() *Call {
	if x, ok := m.GetContent().(*Packet_Call); ok {
		return x.Call
	}
	return nil
}

func (m *Packet) GetReply() *Reply {
	if x, ok := m.GetContent().(*Packet_Reply); ok {
		return x.Reply
	}
	return nil
}

func (m *Packet) GetPush() []byte {
	if x, ok := m.GetContent().(*Packet_Push); ok {
		return x.Push
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Packet) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Packet_Call)(nil),
		(*Packet_Reply)(nil),
		(*Packet_Push)(nil),
	}
}

func init() {
	proto.RegisterEnum("ws.Packet_ContentType", Packet_ContentType_name, Packet_ContentType_value)
	proto.RegisterType((*Error)(nil), "ws.Error")
	proto.RegisterType((*Call)(nil), "ws.Call")
	proto.RegisterType((*Reply)(nil), "ws.Reply")
	proto.RegisterType((*Packet)(nil), "ws.Packet")
}

func init() { proto.RegisterFile("packet.proto", fileDescriptor_e9ef1a6541f9f9e7) }

var fileDescriptor_e9ef1a6541f9f9e7 = []byte{
	// 312 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x91, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0x9b, 0x98, 0xf4, 0xcf, 0xa4, 0x14, 0x59, 0x44, 0x17, 0x0f, 0x52, 0x73, 0xea, 0x29,
	0x85, 0x8a, 0xe0, 0xc9, 0x43, 0x8b, 0x50, 0x3c, 0xa8, 0xac, 0x9e, 0x7a, 0xdb, 0x26, 0x4b, 0x1b,
	0xdc, 0x66, 0x97, 0xdd, 0x0d, 0xa1, 0x9f, 0xce, 0xaf, 0x26, 0xb3, 0x69, 0x31, 0xe0, 0x6d, 0x76,
	0xde, 0x9b, 0x97, 0xf7, 0x23, 0x30, 0xd6, 0x3c, 0xff, 0x16, 0x2e, 0xd3, 0x46, 0x39, 0x45, 0xc2,
	0xc6, 0xa6, 0x8f, 0x10, 0xbf, 0x18, 0xa3, 0x0c, 0x21, 0x10, 0xe5, 0xaa, 0x10, 0x34, 0x98, 0x06,
	0xb3, 0x98, 0xf9, 0x99, 0x50, 0x18, 0x1c, 0x84, 0xb5, 0x7c, 0x27, 0x68, 0x38, 0x0d, 0x66, 0x23,
	0x76, 0x7e, 0xa6, 0xcf, 0x10, 0xad, 0xb8, 0x94, 0x64, 0x02, 0x61, 0x59, 0x9c, 0x6e, 0xc2, 0xb2,
	0xc0, 0x94, 0x8a, 0x1f, 0xce, 0x76, 0x3f, 0xe3, 0xae, 0xe0, 0x8e, 0xd3, 0x8b, 0x69, 0x30, 0x1b,
	0x33, 0x3f, 0xa7, 0x1b, 0x88, 0x99, 0xd0, 0xf2, 0xf8, 0x2f, 0xe0, 0xea, 0x64, 0xc6, 0x80, 0xf1,
	0xba, 0xd7, 0xda, 0xc9, 0x3d, 0xc4, 0x02, 0x5b, 0xfa, 0x8c, 0x64, 0x31, 0xca, 0x1a, 0x9b, 0xf9,
	0xda, 0xeb, 0x1e, 0x6b, 0x95, 0xe5, 0x10, 0xfa, 0x46, 0xd8, 0x5a, 0xba, 0xf4, 0x27, 0x80, 0xfe,
	0x87, 0xe7, 0x24, 0x4f, 0x90, 0xe4, 0xaa, 0x72, 0xa2, 0x72, 0x5f, 0x47, 0xdd, 0xb2, 0x4d, 0x16,
	0xd7, 0x78, 0xdd, 0x1a, 0xb2, 0xd5, 0x9f, 0xca, 0xba, 0x56, 0x72, 0x07, 0x51, 0xce, 0xa5, 0xf4,
	0x3d, 0x92, 0xc5, 0x10, 0x4f, 0x10, 0x18, 0x1b, 0xe1, 0x1e, 0x1b, 0x19, 0x04, 0xe8, 0x36, 0xf2,
	0x44, 0xd8, 0xc8, 0x2b, 0x88, 0xa2, 0x6b, 0xbb, 0xa7, 0xd1, 0x19, 0x05, 0x5f, 0xe9, 0x0d, 0x24,
	0x9d, 0x8f, 0x92, 0x21, 0x44, 0xaf, 0x9f, 0xef, 0x6f, 0x97, 0xbd, 0xe5, 0x08, 0x06, 0x27, 0x61,
	0x79, 0xbb, 0xa1, 0xbb, 0xd2, 0xed, 0xeb, 0x6d, 0x96, 0xab, 0xc3, 0x7c, 0xa7, 0x74, 0xbd, 0x9d,
	0x37, 0x65, 0x25, 0xe6, 0x8d, 0xdd, 0xf6, 0xfd, 0xbf, 0x7b, 0xf8, 0x0d, 0x00, 0x00, 0xff, 0xff,
	0x07, 0x2f, 0x8c, 0x19, 0xcb, 0x01, 0x00, 0x00,
}
